"""make_device_target_id_nullable

Revision ID: 0fc7079ed2d4
Revises: 
Create Date: 2026-06-23 18:55:59.574718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc7079ed2d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'target_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('devices_target_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'targets', ['target_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_target_id_fkey', 'devices', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.alter_column('devices', 'target_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
