"""add_field_photo_sessions_and_enrich_device_photos

Revision ID: 5ecfc4ca48b2
Revises: d4e5f6a7b8c9
Create Date: 2026-07-14 17:24:07.896261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecfc4ca48b2'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_photos', sa.Column('photo_step', sa.Enum('context', 'environment', 'front', 'back', 'side', 'serial_imei', 'seal', 'additional', name='photo_step_enum'), nullable=True))
    op.add_column('device_photos', sa.Column('sha256_hash', sa.String(length=64), nullable=True))
    op.add_column('device_photos', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('device_photos', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('device_photos', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('device_photos', sa.Column('capture_device_model', sa.String(length=200), nullable=True))
    op.add_column('device_photos', sa.Column('field_device_record_id', sa.UUID(), nullable=True))
    op.add_column('device_photos', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_device_photos_field_device_record_id'), 'device_photos', ['field_device_record_id'], unique=False)
    op.create_index(op.f('ix_device_photos_session_id'), 'device_photos', ['session_id'], unique=False)
    op.create_foreign_key(None, 'device_photos', 'field_photo_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'device_photos', 'field_device_records', ['field_device_record_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_photos', type_='foreignkey')
    op.drop_constraint(None, 'device_photos', type_='foreignkey')
    op.drop_index(op.f('ix_device_photos_session_id'), table_name='device_photos')
    op.drop_index(op.f('ix_device_photos_field_device_record_id'), table_name='device_photos')
    op.drop_column('device_photos', 'session_id')
    op.drop_column('device_photos', 'field_device_record_id')
    op.drop_column('device_photos', 'capture_device_model')
    op.drop_column('device_photos', 'captured_at')
    op.drop_column('device_photos', 'longitude')
    op.drop_column('device_photos', 'latitude')
    op.drop_column('device_photos', 'sha256_hash')
    op.drop_column('device_photos', 'photo_step')
    # ### end Alembic commands ###
