"""add_is_op_admin_to_operation_users

Revision ID: 7b1e39702b25
Revises: c2d3e4f5a6b1
Create Date: 2026-07-09 22:39:23.082339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1e39702b25'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_member_user_unique', table_name='deployment_team_members', postgresql_where='(user_id IS NOT NULL)')
    op.add_column('operation_users', sa.Column('is_op_admin', sa.Boolean(), server_default='false', nullable=False, comment='Se True, este usuário é administrador desta operação específica'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_users', 'is_op_admin')
    op.create_index('ix_team_member_user_unique', 'deployment_team_members', ['team_id', 'user_id'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    # ### end Alembic commands ###
