"""make_device_operation_id_nullable

Revision ID: ed01c7fdb518
Revises: 5ecfc4ca48b2
Create Date: 2026-07-16 15:12:27.918937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed01c7fdb518'
down_revision: Union[str, Sequence[str], None] = '5ecfc4ca48b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'operation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('devices_operation_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'operations', ['operation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_operation_id_fkey', 'devices', 'operations', ['operation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('devices', 'operation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
